---
- hosts: all
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx-light state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
